services:
  main_services:
    container_name: ${STACK_NAME}-main-services
    build:
      context: ./main-services
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./main-services/src
    ports:
      - '${MAIN_SERVICES_PORT:-3000}:3000'
    restart: unless-stopped
    environment:
      TZ: Pacific/Auckland
      LANG: en_NZ.UTF-8
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME}
      MAIN_SERVICES_URL: ${MAIN_SERVICES_URL}
      SCRAPE_SERVICE_URL: ${SCRAPE_SERVICE_URL}
      SCRAPE_SEVERE_WEATHER_OUTLOOK_URL: ${SCRAPE_SEVERE_WEATHER_OUTLOOK_URL}
      SCRAPE_THUNDERSTORM_OUTLOOK_URL: ${SCRAPE_THUNDERSTORM_OUTLOOK_URL}
      METSERVICE_CAP_URL: ${METSERVICE_CAP_URL}
      ABLY_CHANNEL_NAME: ${ABLY_CHANNEL_NAME}
      ABLY_API_KEY: ${ABLY_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      ANTHROPIC_MODEL: ${ANTHROPIC_MODEL}
    networks:
      - app-network
  scrape_services:
    container_name: ${STACK_NAME}-scrape-services
    build:
      context: ./scrape-services
      dockerfile: Dockerfile
    ports:
      - '${SCRAPE_SERVICES_PORT:-4000}:4000'
    restart: unless-stopped
    environment:
      TZ: Pacific/Auckland
    networks:
      - app-network
  ui:
    container_name: ${STACK_NAME}-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    depends_on:
      - main_services
      - scrape_services
      - mongodb
    ports:
      - '${UI_PORT:-3001}:3001'
    restart: unless-stopped
    environment:
      TZ: Pacific/Auckland
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME}
      MAIN_SERVICES_URL: ${MAIN_SERVICES_URL}
      SCRAPE_SERVICE_URL: ${SCRAPE_SERVICE_URL}
      SCRAPE_SEVERE_WEATHER_OUTLOOK_URL: ${SCRAPE_SEVERE_WEATHER_OUTLOOK_URL}
      SCRAPE_THUNDERSTORM_OUTLOOK_URL: ${SCRAPE_THUNDERSTORM_OUTLOOK_URL}
      METSERVICE_CAP_URL: ${METSERVICE_CAP_URL}
      ABLY_CHANNEL_NAME: ${ABLY_CHANNEL_NAME}
      ABLY_API_KEY: ${ABLY_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      ANTHROPIC_MODEL: ${ANTHROPIC_MODEL}
    networks:
      - app-network
  mongodb:
    image: mongo:latest
    container_name: ${STACK_NAME}-mongodb
    command:
      - --quiet
      - --logpath
      - /data/db/mongod.log
      - --logappend
    ports:
      - '${MONGODB_PORT:-27017}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      TZ: Pacific/Auckland
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongodb_data: